### ISSUE TITLE
Problems with epoll backend for ioqueue

### ISSUE THREAD

**Issue by bennylp** [bennylp/pjproject#2]
This issue contains EPOLLIN bug fix and other bug fixes and enhancements to epoll and other ioqueues.

### `EPOLLIN` bug in epoll ioqueue

The `EPOLLIN` flag is always set in the epoll as soon as `pj_ioqueue_register_sock()` is called, regardless of whether there is any call to `pj_ioqueue_recv()`. This causes any incoming packet to trigger epoll event, and because there is no pending `recv()`, the packet will not be read and the epoll event will keep coming, potentially causing busy loop in epoll ioqueue (note: there is workaround that calls *sleep()* when the epoll ioqueue receives an event without any handler to prevent this busy loop, but this only masks the problem).

####  `pj_ioqueue_name()` not updated
On epoll backend, the ioqueue name should return the type of the epoll backend. This is only updated when an ioqueue instance has been created. As the result, when `pj_ioqueue_name()` is called before that, the name is not up to date.

#### New `pj_ioqueue_create2()` API

New API that takes a configuration parameter, `struct pj_ioqueue_cfg`. Currently this allows specifying the default concurrency. With epoll backend, this allows selecting which epoll flags to use (EXCLUSIVE, ONESHOT, plain). In the future, this can be used to further specify ioqueue run-time configuration.

#### More ioqueue unit tests

1. Added new ioqueue stress test in pjlib-test (`ioq_stress_test.c`) to test many ioqueue configurations and scenarios, especially when using multiple threads.
2. Added parallel receive test, `parallel_recv_test()` in `ioq_udp.c`, to analyze the thread effectiveness of the ioqueue (e.g. how many threads are woken up to process one event).
3. Ioqueue testing now tests all supported epoll flags (EXCLUSIVE, ONESHOT, plain).

#### new `ioqueue_add_from_set2()` and `ioqueue_remove_from_set2()`

The new functions allows setting multiple flags in one function call, to reduce the number of syscalls to be made when changing flags.

### PJSIP version

2.12.1

**Comment by jimying** [comment]
oneshot should loop read til EAGAIN (like ET mode)

**Comment by jimying** [comment]
I was wrong, pjmedia transport_udp.c on_read_complete() callback already loop read

**Comment by jimying** [comment]
rearm action should do immediatly after epoll_wait() , in the loop here, https://github.com/bennylp/pjproject/blob/3ade7c9215236f6e182e63531e70768b8257b280/pjlib/src/pj/ioqueue_epoll.c#L757

currently rearm action is in here https://github.com/bennylp/pjproject/blob/3ade7c9215236f6e182e63531e70768b8257b280/pjlib/src/pj/ioqueue_epoll.c#L885

**Comment by jimying** [comment]
I try change and test ok.

https://github.com/jimying/pjproject/commit/a3581b4ff9132284cffee836df81a95bebd7e03c

**Comment by jimying** [comment]
has update, fix  miss key lock.  
https://github.com/jimying/pjproject/commit/29ce83c2f486fd1021d412648e999fdcec6272b4

**Comment by jimying** [comment]
> I think the problem with epoll ioqueue is EPOLLIN is **always** set to the epoll, regardless of whether there is an async recv()/recvfrom() or not. I think that's what causing all the problems above. That has got to be fixed first. Then we can check other scenarios e.g. ONESHOT etc.

Maybe can change select,    keep fd always in rfdset,  check if it has the same problem

**Comment by bennylp** [comment]
Merged in main repo (3188)
